# NOTE:2行目ははcommitしないこと
hf_token: "dummy"  # Hugging Face Token を指定

model:
  model_id: "llm-jp/llm-jp-3-13b"
  adapter_id: "MakeNoah/llm-jp-3-13b-finetune"  # Hugging FaceにアップロードされたLoRAアダプタID 
  use_bf16: false  # bf16を使用するかどうか
  bit_width: 14  # 量子化するビット幅 (例: 12, 14)
  enable_cpu_offload: true  # CPUオフロードを有効化するかどうか
  dtype: null  # 自動設定
  save_path: "./saved_model"  # 保存先ディレクトリ



data:
  input_file: "./elyza-tasks-100-TV_0.jsonl"
  output_file_template: "./results/{adapter_id}_output.jsonl"

generation:
  max_new_tokens: 128
  use_cache: true
  do_sample: false
  repetition_penalty: 1.2
